import { readFileSync, writeFileSync, existsSync } from 'fs';
import { join } from 'path';

const DOCS_DIR = process.argv[2] || 'C:/VJDS/docs/product-exploration';
const OUTPUT_FILE = join(process.cwd(), 'api', 'research-context.ts');

const EXCLUDE = new Set(['food-database-v1.md']);

// Reading order per HANDOFF.md
const FILE_ORDER = [
  'HANDOFF.md',
  'TRIVEDA_SPEC.md',
  '00-executive-summary.md',
  '01-behavioral-psychology.md',
  '02-traditional-medicine-opportunities.md',
  '03-codebase-audit.md',
  '04-synthesized-visions.md',
  '05-contrarian-angles.md',
  '06-adversarial-review.md',
  '07-final-vision.md',
  '08-creative-wildcard.md',
  'three-traditions/00-executive-summary.md',
  'three-traditions/01-case-against.md',
  'three-traditions/02-case-for.md',
  'three-traditions/03-multi-framework-research.md',
  'three-traditions/04-synthesis.md',
  'three-traditions/05-devils-advocate.md',
  'three-traditions/06-final-vision.md',
  'three-traditions/07-creative-push.md',
  'challenges/00-executive-summary.md',
  'challenges/01-domain-expertise-gap.md',
  'challenges/02-content-repetition.md',
  'challenges/03-beyond-llm-wrapper.md',
  'challenges/04-beyond-portfolio.md',
  'tech/00-executive-summary.md',
  'tech/01-deterministic-engines.md',
  'tech/02-ml-data-systems.md',
  'tech/03-knowledge-graph.md',
];

let output = '';
let fileCount = 0;
let totalChars = 0;

for (const file of FILE_ORDER) {
  if (EXCLUDE.has(file)) continue;

  const fullPath = join(DOCS_DIR, file);
  if (!existsSync(fullPath)) {
    console.warn(`Warning: skipping missing file: ${file}`);
    continue;
  }

  const content = readFileSync(fullPath, 'utf-8');
  output += `\n=== FILE: ${file} ===\n\n${content}\n`;
  fileCount++;
  totalChars += content.length;
}

const tsContent = `// Auto-generated by scripts/build-context.ts — do not edit manually
// ${fileCount} files, ${totalChars.toLocaleString()} characters
export const RESEARCH_DOCS: string = ${JSON.stringify(output)};
`;

writeFileSync(OUTPUT_FILE, tsContent, 'utf-8');
console.log(`Generated api/research-context.ts`);
console.log(`  ${fileCount} files, ${totalChars.toLocaleString()} chars, ${(Buffer.byteLength(tsContent) / 1024).toFixed(0)}KB`);
