import { readFileSync, writeFileSync } from 'fs';
import { join } from 'path';

const KNOWLEDGE_BASE = join(process.cwd(), 'docs', 'TRIVEDA_KNOWLEDGE_BASE.md');
const OUTPUT_FILE = join(process.cwd(), 'api', 'research-context.ts');

const content = readFileSync(KNOWLEDGE_BASE, 'utf-8');

const tsContent = `// Auto-generated by scripts/build-context.ts — do not edit manually
// Consolidated knowledge base: ${content.split(/\s+/).length.toLocaleString()} words, ${content.length.toLocaleString()} characters
export const RESEARCH_DOCS: string = ${JSON.stringify(content)};
`;

writeFileSync(OUTPUT_FILE, tsContent, 'utf-8');
console.log(`Generated api/research-context.ts`);
console.log(`  ${content.split(/\s+/).length.toLocaleString()} words, ${content.length.toLocaleString()} chars, ${(Buffer.byteLength(tsContent) / 1024).toFixed(0)}KB`);
